name: Unity Test Runner

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      # Runs the primary testing suite from https://github.com/marketplace/actions/unity-test-runner
      - name: Unity - Test runner
        # You may pin to the exact commit or the version.
        # uses: game-ci/unity-test-runner@e1be8325cd37b6e496c5b8949d9177a5f4c7766a
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        with:
          # Version of unity to use for testing the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt
          unityVersion: auto
          # Path to the Unity project to be tested.
          # projectPath: # optional
          # The type of tests to be run by the test runner.
          # testMode: # optional, default is all
          # Path where test artifacts should be stored.
          # artifactsPath: # optional, default is artifacts
          # Initialises Docker using the hosts network.
          # useNetworkHost: # optional
          # Extra parameters to configure the Unity editor run.
          # customParameters: # optional
