name: GameCI Suite

on:
  # Disabling for now
  #pull_request: {}
  #push: { branches: [main] }
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0-alpha-2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
